{% set name = "climada-petals" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/climada_petals-{{ version }}.tar.gz
  sha256: ba9ab347bf7c9cab32107a9bb4d5007a5f4ff44ec2b99ccc272c41abc3c4fc7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python =3.9
    - setuptools-scm
    - pip
  run:
    - python =3.9
    - climada =4.1
    - osm-flex =1.1
    - overpy =0.7
    - pymrio =0.5
    - scikit-image =0.22

test:
  imports:
    - climada_petals
  source_files:
    - climada_petals
  commands:
    - {{ PYTHON }} -m pip install . -vv  # Make sure osm-flex is installed
    - pip check
    - pytest climada_petals/test/test_cropyield_integr.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/CLIMADA-project/climada_petals
  summary: "CLIMADA-Petals: The extension module for CLIMADA (probabilistic natural catastrophe impact model in Python)"
  description: |
    CLIMADA Petals generates different types of hazards and contains more specialized
    applications than the CLIMADA Core module. CLIMADA stands for CLIMate ADAptation and
    is a probabilistic natural catastrophe impact model, that also calculates averted
    damage (benefit) thanks to adaptation measures of any kind.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://climada-petals.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - peanutfun
