{% set name = "climada-petals" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/climada_petals-{{ version }}.tar.gz
  sha256: d8d10ebe1bd1420422ed4a47d90169d05c74d36cecb9dce75a956df113f51b06

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<3.12
    - climada =5.0
    - cdsapi =0.6
    - importlib-metadata =7.2
    - meson-python =0.15
    - osm-flex =1.1
    - overpy =0.7
    - pymrio =0.5
    - rioxarray =0.15
    - ruamel.yaml =0.18
    - scikit-image =0.25
    - xesmf =0.8

test:
  imports:
    - climada_petals
  source_files:
    - climada_petals
  commands:
    - pip check
    - pytest climada_petals/test/test_cropyield_integr.py
  requires:
    - pip =24.0
    - pytest
    - pytest-json-report
    - python {{ python_min }}

about:
  home: https://github.com/CLIMADA-project/climada_petals
  summary: "CLIMADA-Petals: The extension module for CLIMADA (probabilistic natural catastrophe impact model in Python)"
  description: |
    CLIMADA Petals generates different types of hazards and contains more specialized
    applications than the CLIMADA Core module. CLIMADA stands for CLIMate ADAptation and
    is a probabilistic natural catastrophe impact model, that also calculates averted
    damage (benefit) thanks to adaptation measures of any kind.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://climada-petals.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - emanuel-schmid
    - peanutfun
